version: '3'

services:
  db:
    image: 'postgres:11-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    depends_on:
      - 'db'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/project'
    environment:
      - RUBYOPT=-W:no-deprecated -W:no-experimental
    env_file:
      - '.env'

volumes:
  postgres:
